---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1546269/public_html/nampi26/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .htaccess $DEPLOYPATH
    - /bin/cp -R public/.htaccess $DEPLOYPATH/public/
